version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: github-emoji
    versions:
    - 1.1.1
